DROP TABLE IF EXISTS TaskClassOfTask CASCADE;
DROP TABLE IF EXISTS Task CASCADE;
DROP TABLE IF EXISTS PriorityClass CASCADE;
DROP TABLE IF EXISTS TaskClass CASCADE;
DROP TABLE IF EXISTS Person CASCADE;
